# fly.toml app configuration file generated for bdist-bankapi on 2023-11-07T17:18:56Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bdist-bank-api"
primary_region = "mad"
swap_size_mb = 256

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
